[package]
name = "save-model-to-safetensor"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.21.0", features = ["std", "wgpu", "accelerate", "autodiff", "store"] }
burn-store = { version = "0.21.0"}
clap = { version = "4.6.7", features = ["derive"] }
tiktoken ={ version = "4.1.2" }
gpt-helpers ={ path = "../gpt-helpers" }
